### ISSUE TITLE
AppInfo函数不存在或错误(-105)

### ISSUE THREAD

**Issue by rindybo** [Jie2GG/Native.Csharp.Frame#106]
请问出现这个错误怎么解决，AppInfo已经改成public 还是不行

com.aa.bb.demo.dll 加载失败！错误：AppInfo函数不存在或错误(-105)

		[DllExport (ExportName = "AppInfo", CallingConvention = CallingConvention.StdCall)]
		public static string AppInfo ()
		{
			// 请勿随意修改
			// 
			Common.AppName = "酷Q样例应用";
			Common.AppVersion = Version.Parse ("1.0.0");		

			//
			// 当前项目名称: com.aa.bb.demo
			// Api版本: 9

			return string.Format ("{0},{1}", 9, "com.aa.bb.demo");
		}

**Comment by rindybo** [comment]
用的是Pro版本

**Comment by Jie2GG** [comment]
请克隆最新正式版，按照WIKI使用
