### ISSUE TITLE
Wiki请求更新

### ISSUE THREAD

**Issue by ly123567** [Jie2GG/Native.Csharp.Frame#108]
目前的代码的依赖包已经是

> using Native.Csharp.Sdk.Cqp.EventArgs;
using Native.Csharp.Sdk.Cqp.Interface;

而Wiki第05部分的代码依然是

> using Native.Csharp.App.EventArgs;
using Native.Csharp.App.Interface;

这对刚接触框架的新手可能不是太友好，请求修改。（三四个月没拿它写插件都差点不会用了。。T_T）

另外就是可以考虑对Event文件夹中的文件，可以直接从模版新建(有个很老的C#框架用到了这种方法)，当然如果太麻烦就算了Orz

**Comment by Jie2GG** [comment]
ok, 等新版出来整个 WIKI 就改掉

**Comment by gitlsl** [comment]
更新很频繁,已star很久了
提个建议:直接上 .net4.7.2(虽然4.6已经符合.netstand2.0,但微软建议上这个)  或者4.8(win10都自带了),长痛不如短痛直接到最新吧

**Comment by Jie2GG** [comment]
SDK在 Windows 下使用的时候, 你可以随意升级版本, 只要编译不报错基本都可以正常使用. 只要稍微注意一下 Native.Csharp.Tool.SQLite.
