### ISSUE TITLE
GroupInfo接口查询的群名需要转义

### ISSUE THREAD

**Issue by d8kzdzt** [Jie2GG/Native.Csharp.Frame#115]
群名称也有转义符存在。
建议:
this.Name = CQApi.CQDeCode(reader.ReadString_Ex (CQApi.DefaultEncoding));

**Comment by Jie2GG** [comment]
感谢反馈. 之后优化

**Comment by Jie2GG** [comment]
> 群名称也有转义符存在。
> 建议：
> this.Name = CQApi.CQDeCode（reader.ReadString_Ex（CQApi.DefaultEncoding））;

您好, 目前的最新 Test 版已经在解决这个问题, 您可以再试一试是否还有这个问题的存在
