### ISSUE TITLE
群请求：申请入群相关问题

### ISSUE THREAD

**Issue by PoH98** [Jie2GG/Native.Csharp.Frame#121]
想要询问如何批准人入群，另外目前的文档还是不怎么足够的样子啊

**Comment by traceless0929** [comment]
如下：
```c#
public class Event_GroupAddRequest : IGroupAddRequest
    {

        public void GroupAddRequest(object sender, CQGroupAddRequestEventArgs e)
        {
            e.CQApi.SetGroupAddRequest(e.ResponseFlag,e.SubType, Native.Csharp.Sdk.Cqp.Enum.CQResponseType.PASS, "备注");

        }
    }
```

SetGroupAddRequest参数说明：

string tag : 加群请求的 flag（需从上报的数据中获得）
CQGroupAddRequestType request : 请求类型 需要和上报消息中的 sub_type 字段相符
CQResponseType response ： 反馈类型 是否同意请求／邀请
string appendMsg ：拒绝理由（仅在拒绝时有效）

**Comment by traceless0929** [comment]
好友请求、讨论组请求等 同理

**Comment by PoH98** [comment]
OK感谢

**Comment by PoH98** [comment]
抱歉再次麻烦，目前已测试相关功能，然而无效，有人申请时候不会触发该事件，酷Q也没有任何的日志显示。已经确认json是存在相关权限请求，而且也已经运行.tt文件

**Comment by Jie2GG** [comment]
若酷Q没有相关日志, 则表示酷Q未调用事件接口.

**Comment by PoH98** [comment]
那该如何解决？是否为酷Q问题？目前本人在开发的插件网址是[这个](https://github.com/PoH98/QQBotXClashOfClans)，代码方面已经根据Wiki进行开发

**Comment by Jie2GG** [comment]
酷Q未调用 SDK 已公开的事件, 属于酷Q层面的问题. 可以去酷Q社区提 Issue

**Comment by PoH98** [comment]
好的，感谢回答

**Comment by cqbef** [comment]
https://github.com/PoH98/QQBotXClashOfClans/blob/master/Native.Csharp.Frame-Final/Native.Csharp/App/Event/Event_AppMain.cs#L54

加上
```cs
container.RegisterType<IReceiveAddGroupRequest, Event_MemberAddGroup>("群添加请求处理");
```

LibExport.tt 需要重新執行一次

https://github.com/PoH98/QQBotXClashOfClans/blob/master/Native.Csharp.Frame-Final/Native.Csharp/App/Core/LibExport.cs

可以看到並未加入``群添加请求处理``事件

**Comment by PoH98** [comment]
那个是我还原了旧版本的框架（3.4版本），新版本的已经执行和加上依旧是不行

**Comment by cqbef** [comment]
如果還有需要，可以創分支並把新版本提交幫你核對。

**Comment by PoH98** [comment]
目前估计暂时不会再更新框架，之前测试还出现过个串流未完成的问题，旧版本的挺稳定的，至少群申请可以批准

**Comment by cqbef** [comment]
了解，新版本還需要時間改善及修復異常。如果將來在新版本使用時發現問題，歡迎再次提交，一起改善。

**Comment by PoH98** [comment]
我个人意见吧，感觉旧版本比新的更容易用，至少不会全部东西都绑定在Event上面

**Comment by cqbef** [comment]
關於CQApi，CQLog新版本的變化差異
有不少用戶表示實現方式比較麻煩，正如你所說需要在事件下調用 ``e.CQApi`` ``e.CQLog`` ``e.Messages``
我們實現調用過程時，最終可能還是需要手動加一个3.X版本的 ``Common`` static class，
而在新版本提供的DEMO裏其實也是這樣實現。[Demo - Common.cs#L23](https://github.com/Jie2GG/Native.Csharp.Frame/blob/Demo/Core/Common.cs#L23)

作者作出的回應是自己的代碼自己實現，我相信作者是想在既精簡的同時，提供盡可能有用的方法調用而又不固定用戶使用方法。

參考在過去的SDK版本直到現時4.X版本的演變，從**2.X**版本的固定事件類到**3.X**注冊事件方式直到現在**4.X**的事件驅動方式，作者都在不斷減少實作並加強SDK功能及更多的處理方法包括**1.X**版本的酷Q表情擴展；**2.X**版本的Tool類分離及UI项目移除；**3.X**版本的消息解析；**4.X**版本的正则事件並加強消息解析的調用等等都靠着SDK內部優化處理着。

現時的優勢是精簡充實的SDK調用。雖然實作的地方相對上多了，但是同樣地把可能不必要的地方移除了，所有行為基於事件驅動實作的好處是更核心地調用SDK，回歸SDK的本質。
而更大的改善是在現體系下，我們的項目可以以引用關系把事件實作的核心脫離SDK，使到更新SDK時不再必要考慮更新文件的取替，SDK文件歸類到SDK,核心項目是不必替換的。

具體地說，在3.X版本``Native.Csharp`` 是我們的主項目，所有事件均在Native.Csharp裏實現。
而在4.X版本,``Native.Csharp``完全可以空構作注冊管理用途，我們的核心實現，是在其他项目中處理着事件。可以參看[Demo分支](https://github.com/Jie2GG/Native.Csharp.Frame/tree/Demo)，Native.Csharp被作為Agent，Core才是我們的项目，这种結構上明顯地提高可控度和更方便管理。
