### ISSUE TITLE
多个该框架打包而成的CPK会由于加载时间过长报错

### ISSUE THREAD

**Issue by traceless0929** [Jie2GG/Native.Csharp.Frame#62]
多个该框架打包而成的CPK会由于加载时间过长报错，
实例：
A应用，Event_AppStatus.AppEnable中为空（框架默认内容，没有做任何修改）
B应用，Event_AppStatus.AppEnable中加载了一些配置，

现象：A加载成功，B报加载错误。

机器配置：windows server 2008 R2
CPU: 2.3G Xeon E5-26xx v3
Memory:1GB

初步判断是
Event_AppStatus.AppEnable及框架在该方法之前进行初始化的时间过长。

可以联系我采集详细数据

**Comment by Jie2GG** [comment]
麻烦提供一些详细的数据供分析

**Comment by Jie2GG** [comment]
可以进QQ群: 711841640

**Comment by traceless0929** [comment]
根据群中大佬推荐，使用该兼容性插件解决问题。
[.Net兼容插件](https://cqp.cc/forum.php?mod=viewthread&tid=42920)
